---
title: "Planificación"
sidebar: false
toc: false
page-layout: full
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

## Forma general de funcionamiento

Este curso se compone de tres actividades principales a la semana:

-   <i class="fas fa-chalkboard-teacher"></i> [**Clases lectivas presenciales**](): los jueves de 14:30 a 16:00 en Sala 34, donde en base a las lecturas correspondientes a esa semana se presentará un resumen de los contenidos principales y se resolverán dudas.

-   <i class="fas fa-user-edit"></i> [**Talleres prácticos**](): Jueves seguido a las clases lectivas, de 16:15 a 17:45 en sala 45 (computación).

-   <i class="fas fa-book-reader"></i> [**Lecturas**](): cada sesión lectiva tiene una lectura obligatoria asignada a la semana, la que se encuentra a disposición en esta página.

<br>

Esta programación se encuentra ajustada posterior a la toma de la facultad. Acá link a [**programación original**](https://multinivel-facso.netlify.app/schedule) **(pre-toma)**

+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       |       | # <i class="fas fa-chalkboard-teacher"></i>                                                               | # <i class="fas fa-book-reader"></i>                                                                                                        | # <i class="fas fa-user-edit"></i>                    |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
| Marzo | 13    | [Introducción - Repaso inferencia](/slides/01-mlmintro.html)                                              | [Moore: Comprensión de los datos](https://multivariada.netlify.app/docs/lecturas/moore_comprensiondelosdatos.pdf)                           | Práctico 1: Repaso inferencia                         |       |
|       |       |                                                                                                           |                                                                                                                                             |                                                       |       |
|       |       |                                                                                                           | [Ritchey cap. 6-9](https://correlacional.netlify.app/files/textos/Ritchey.pdf)                                                              |                                                       |       |
|       |       |                                                                                                           |                                                                                                                                             |                                                       |       |
|       |       |                                                                                                           | [Revisar presentación sobre test de hipótesis del curso estadística correlacional](https://correlacional.netlify.app/content/05-content)    |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 20    | [Repaso regresión](/slides/02-regresion.html)                                                             | [Finch cap. 1](/files/readings/finch_etal%202014cap123.pdf)                                                                                 | Práctico 2: Repaso regresion                          |       |
|       |       |                                                                                                           |                                                                                                                                             |                                                       |       |
|       |       |                                                                                                           | [Ritchey cap. 14-15](https://correlacional.netlify.app/files/textos/Ritchey.pdf)                                                            |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 27    | [Taller versionamiento y repositorios (Git/Github)](https://martin-venegas-m.github.io/taller-git-uch/#1) |                                                                                                                                             | Práctico 3: Github                                    |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
| Abril | 03    | [Estimación en distintos niveles](/slides/04-primera_est.html)                                            | [Coleman 1986](/files/readings/coleman1986.pdf)                                                                                             | Práctico 4: Datos agregados y correlación intra clase |       |
|       |       |                                                                                                           |                                                                                                                                             |                                                       |       |
|       |       |                                                                                                           | [Finch 2.1 - 2.3](/files/readings/finch_etal%202014cap123.pdf)                                                                              |                                                       |       |
|       |       |                                                                                                           |                                                                                                                                             |                                                       |       |
|       |       |                                                                                                           | [A Test of Durkheim's Theory of Suicide--Without Committing the "Ecological Fallacy"](files/readings/Poppel-TestDurkheimsTheory-1996.pdf)   |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 10    | [MLM y correlación intra clase](/slides/05-varianzasICC.html)                                             | [Finch 2.4 - 2.9](/files/readings/finch_etal%202014cap123.pdf)                                                                              | Práctico 5: Estimación modelos multinivel             |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 17    | Suspensión por toma                                                                                       |                                                                                                                                             |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 24    | Suspensión por toma                                                                                       |                                                                                                                                             |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
| Mayo  | 01    | Suspensión por toma                                                                                       |                                                                                                                                             |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 08    | Suspensión por toma                                                                                       |                                                                                                                                             |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 15    | [Repaso\                                                                                                  | [O'Conell & McCoach 7, Evaluating model fit and adequacy](https://multinivel.netlify.app/readings/OConnellchap7.pdf)                        | Asesorías grupos                                      |       |
|       |       | Ajuste y reporte](/slides/06-ajuste_reporte.html)                                                         |                                                                                                                                             |                                                       |       |
|       |       |                                                                                                           | [O'Conell & McCoach 11, Reporting results from multilevel](https://multinivel.netlify.app/readings/OConnellchap8.pdf)                       |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 22    | Predicción de efectos aleatorios                                                                          | [Aguinis et al (2013) Best practices MLM interactions](https://multinivel.netlify.app/readings/aguinis2013crosslevel.pdf)                   |                                                       |       |
|       |       |                                                                                                           |                                                                                                                                             |                                                       |       |
|       |       | Interacciones entre niveles                                                                               | [Rohback & Legler (2020) Chap. 8 Multilevel Models](/files/readings/Roback&Legler2020BeyondMultipleLinearRegression-Chapter8Multilevel.pdf) |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       |       |                                                                                                           |                                                                                                                                             | Miércoles 28 \| Entrega trabajo 1 \|                  |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 29    | Centrado                                                                                                  | [Enders & Tofighi 2007) Centering predictor variables MLM](https://multinivel.netlify.app/readings/enderstofighi.pdf)                       |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
| Junio | 05    | Casos influyentes, logística y 3 niveles                                                                  | [Catching Up on Multilevel Modeling](https://www.annualreviews.org/doi/10.1146/annurev-psych-020821-103525)                                 |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 12    | Asesorías trabajos                                                                                        |                                                                                                                                             |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 19    | Presentación trabajos                                                                                     |                                                                                                                                             |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
|       | 26    | Presentación trabajos                                                                                     |                                                                                                                                             | Entrega trabajo 2                                     |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+
| Julio | 01    | Examen                                                                                                    |                                                                                                                                             |                                                       |       |
+-------+-------+-----------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------+-------+