---
title: Programa
lang: es
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

::: {.grid .course-details .course-details-smaller}

::: {.g-col-6}

### Profesor

- {{< fa user >}} &nbsp; [{{< var instructor.name >}}]({{< var instructor.url >}})
- {{< fa university >}} &nbsp; {{< var instructor.office >}}
- {{< fa envelope >}} &nbsp; <a href="mailto:juancastillov@uchile.cl">juancastillov@uchile.cl</a>
- {{< fa calendar-check >}} &nbsp; [Agendar reunión]({{< var instructor.appointment_url >}})
:::

::: {.g-col-6}
### Detales del curso

- {{< fa calendar >}} &nbsp; {{< var course.days >}}
- {{< fa calendar-alt >}} &nbsp; {{< var course.dates >}}
- {{< fa clock >}} &nbsp; {{< var course.time >}}
- {{< fa location-dot >}} &nbsp; {{< var course.location >}}
- {{< fa brands slack >}} &nbsp; [Slack]({{< var course.slack >}})
:::

:::


## Descripción general

Partiendo desde la concepción de **Ciencia Abierta** (Open Science) y de investigación reproducible, este curso presenta formas alternativas a la manera tradicional de concebir la generación de conocimiento de manera cerrada y competitiva, y desde ahí se proponen y ejercitan una serie de herramientas técnicas en el análisis de datos que facilitan la reproducibilidad, colaboración y comunicación de procesos de investigación.

El curso permitirá a los participantes lograr un producto de investigación (artículo, documento de trabajo) con foco en el análisis de datos realizado de manera abierta y reproducible.

## Propósito general

El quehacer académico muchas veces es criticado por su falta de aporte, transparencia y relevancia para la sociedad, crítica que se acentúa en las ciencias sociales. Desde la academia misma han surgido cuestionamientos sobre la capacidad de un trabajo que sea más abierto y auditable, que favorezca la colaboración entre académic_s y no académic_s, y que se comunique de manera eficiente dentro de la academia y fuera de ella.

Partiendo desde la concepción de Ciencia Abierta (Open Science) y de investigación reproducible, este curso presenta formas alternativas a la manera tradicional de concebir la generación de conocimiento de manera cerrada y competitiva, y desde ahí se proponen y ejercitan una serie de herramientas técnicas que facilitan la reproducibilidad, colaboración y comunicación de procesos de investigación.

El curso se dirige no solamente a aquellos estudiantes con interés principal en la investigación académica, sino  también a quienes se quieran dedicar profesionalmente al análisis y reporte de información y datos sociales, trabajo en equipo multidisciplinario, y al vínculo entre academia y políticas públicas.

## Resultados de aprendizaje

Al finalizar el curso, ud. será capaz de:

- Comprender las limitaciones y problemas de la manera tradicional de realizar investigación social.

- Conocer las herramientas computacionales que permiten y promueven una apertura de los procesos de investigación social

- Conocer los flujos de trabajo reproducibles y transparentes

- Desarrollar un proceso de investigación abierto basado en los propios intereses de investigación, orientados hacia la publicación de un producto académico (artículo, documento de trabajo).

## Contenidos

### Introducción a la ciencia abierta y transparencia

- Cierre y crisis de la ciencia
- Marquetización de la academia y consecuencias para su quehacer
- Propuestas de políticas de apertura científica a nivel internacional

### Unidad 1: Reproducibilidad

1.1 Programación literaria

- Trabajando en texto plano: Introducción a Rmarkdown y Latex
- Generación de reportes dinámicos vía Knitr.
- Gestión de fuentes bibliográficas: Zotero, BibTex y BetterBibTex

1.2 Documentos dinámicos
- Rmarkdown
- Quarto

1.3 Flujos, control y documentación

- Flujos reproducibles (protocolo IPO)
- Control de versiones con Git
- Trabajo colaborativo y versionado con Github

### Unidad 2: Comunicación, registro y publicación

- Pre-registros y planes de pre-analisis
- Publicación abierta vía pre-prints (SoxArxiv) y página web (Github pages)
- Generación de presentaciones dinámicas en Quarto
- Proyectos de investigación en OSF (Open Science Framework)
- Visualización de datos

## Metodología

El curso se organiza en sesiones semanales, con una parte lectiva seguida de una práctica. En la parte lectiva se transmiten y discuten los conceptos centrales de la ciencia abierta. En la parte práctica se aplicarán los conceptos transmitidos en la parte lectiva, además de resolver dudas en el avance de los trabajos de investigación.

El curso estará orientado a que l_s participantes puedan al final generar un producto de investigación con características de apertura científica. Para ello, pueden profundizar en algún trabajo previo que les permita avanzar hacia una publicación académica en un proceso de investigación supervisado y reproducible.

## Evaluación

### Entrega 1 (40%): Ejercicio de reproducibilidad

El objetivo de esta entrega es evaluar la capacidad de los estudiantes para aplicar los conceptos de reproducibilidad en un proyecto de investigación, y para comunicar de manera efectiva el proceso y los resultados de su investigación a través de un reporte dinámico.

Para este ejercicio de reproducibilidad, se les asignará un reporte de resultados de investigación social cuyos datos estén disponibles, y se les pedirá que repliquen el análisis y los resultados presentados en el reporte original, utilizando un flujo de trabajo reproducible basado en el protocolo IPO (Input-Process-Output).

El reporte debe incluir:

- Un repositorio abierto (por ejemplo, en GitHub) que contenga el código y los datos necesarios para reproducir el análisis.
- Un reporte dinámico generado a través de Rmarkdown/Quarto que documente el proceso de investigación, incluyendo la metodología, los resultados y las conclusiones. El reporte debe ser claro y detallado, permitiendo a otros investigadores seguir el mismo proceso y obtener los mismos resultados
- El reporte debe ser presentado de manera clara y estructurada, siguiendo las secciones habituales de un trabajo académico (Resumen, Introducción, Antecedentes conceptuales/empíricos, Metodología, Análisis, Conclusiones)
- El reporte debe ser reproducible, es decir, cualquier persona que tenga acceso al repositorio y al reporte dinámico debe ser capaz de ejecutar el código y obtener los mismos resultados que se presentan en el reporte

### Entrega 2 (10%): Evaluación cruzada de reproducibildiad

Los estudiantes evaluarán de manera cruzada los reportes de reproducibilidad de sus compañeros, utilizando una rúbrica que se les proporcionará. Esta evaluación cruzada permitirá a los estudiantes reflexionar sobre los aspectos clave de la reproducibilidad y la comunicación efectiva en la investigación social, y les brindará la oportunidad de aprender de los enfoques y metodologías utilizados por sus compañeros.

### Entrega 3 (40%): Proyecto Abierto

Los lineamientos de la entrega estarán disponibles próximamente. 


## Requisitos de aprobación

Nota mínima de aprobación: 4,0 (en escala de 1 a 7).

## Palabras clave

Ciencia abierta, reproducibilidad, acceso abierto, transparencia, pre-prints, repositorios, control de versiones, markdown.

## Bibliografía Obligatoria (... o central)

Hay cuatro libros que son centrales para este curso:

- El libro base del curso es ["Transparent and Reproducible Social Science Research"](https://www.ucpress.edu/book/9780520296954/transparent-and-reproducible-social-science-research), de Christensen, G. S., Freese, J., & Miguel, E. (2019). Es lo más cercano a los temas del curso, y como ven muy reciente, del tema no había bibliografía así de especializada hasta el año pasado. Lamentablemente, y también paradojicamente, es un libro no disponible de manera gratuita. Muy recomendable. Comentaremos algunos de sus contenidos en las primeras sesiones introductorias.

- Un segundo texto no tiene relación directa con apertura, pero sí muchos elementos que ayudan para llevar a cabo análisis reproducibles en R: [R for Data Science](https://r4ds.had.co.nz/) (conocido como RDS) de Garrett Grolemund y Hadley Wickham (2017). Afortunadamente tenemos una versión traducida al español y disponible de manera abierta online: ["R para Ciencia de Datos"](https://es.r4ds.hadley.nz/)

- El tercero es más específico para la Unidad 2 sobre escritura en texto plano: ["The Plain Person’s Guide to Plain Text Social Science"](https://kieranhealy.org/files/papers/plain-person-text.pdf), de Kieran Healy en su última version 2019. Para mi gusto uno de los libros inspiradores sobre las implicancias para la escritura del trabajo académico abierto, y escrito por un gran sociólogo.

- Y el cuarto es [R Markdown: The definitive guide](https://bookdown.org/yihui/rmarkdown/), de Yihui Xie, J. J. Allaire & Garrett Grolemund (2019). Abarca los detalles del proceso de investigación reproducible vinculando escritura y análisis, pero con mucho énfasis en publicación y presentación de resultados.

El detalle de otras lecturas sugeridas para cada clase aparece en la página de [Planificación](https://cursos-metodos-facso.github.io/cienciasocialabierta2026/docs/schedule2.html) de las sesiones.

## Software

Como software vamos a utilizar VSC, Quarto, Git/Github, Zotero. VSC es un editor de texto generalizado, con muchas funciones que van más allá del análisis de datos, y que es gratuito y de código abierto. Si bien me parece apropiado para el curso, corresponde decir que la opción por editores también es algo abierto, sobre todo en un curso que tiene que ver con apertura. Otros editores muy usados son [Emacs](https://www.gnu.org/software/emacs/), [Sublime](https://www.sublimetext.com/) y [Atom](https://atom.io/). Si a alguien le interesa podemos hacer alguna sesión adicional sobre Atom, que es el editor que yo uso.

## Planificación de las sesiones y materiales respectivos

Consultar la página [Planificación](https://cursos-metodos-facso.github.io/cienciasocialabierta2026/docs/schedule2.html).

## Inasistencias y atraso en entregas

Los justificativos por ausencia o atraso se realizan en la secretaría de carrera. Lo que la carrera informe como justificado, es lo que se va a considerar en el curso. **No enviar justificativos directamente**, no es necesario ni apropiado para l_s estudiantes tener que exponer situaciones personales.

En caso de atrasos en las entregas se descontará 0.5 por día adicional. Si el trabajo no se entrega luego del tercer día de atraso será calificado con nota 1.0

## Requisitos de aprobación 

Requisitos de eximición a examen:

- contar con un promedio ponderado igual o superior a 5.5
- no tener nota bajo 4.0 en ninguna de las evaluaciones

Requisitos para presentación a examen:

- Podrán presentarse al examen de primera oportunidad los estudiantes que hayan obtenido una calificación final igual o superior a 3.5.

- El examen de segunda oportunidad será para aquellos estudiantes que presenten una nota igual o inferior a 3.5 o aquellos que en el examen de primera oportunidad no hubiesen logrado una nota igual o superior a 4.0.

## Bibliografía Obligatoria 

Capítulos correspondientes a cada sesión se indican en la página de [Planificación](https://cursos-metodos-facso.github.io/cienciasocialabierta2026/docs/schedule2.html).

## VARIOS

- Se espera asistencia y participación activa, tanto a las sesiones lectivas como a las prácticas. 
  
- Se pasará asistencia en todas las sesiones. Quienes tengan menos de un 70% de asistencia y deban rendir examen pasarán directo al de segunda.  

- Sobre situaciones de paro/tomas: este curso electivo se ofrece tanto a estudiantes de pre como de postgrado. Por lo tanto, las actividades docentes se suspenderán por paro o tomas solo en caso que tanto en pre como en postgrado se haya votado y aprobado la medida. De otra manera, las actividades docentes se mantienen, de ser necesario de manera online. 

- Las clases en general se acompañan de documentos de presentación, que estarán disponibles antes de la sesión en la página de Contenidos, y están desarrollados con base en Rmarkdown/Xaringan, y eventualmente en Quarto. Estos documentos no son:

  - “la clase”
  - autoexplicativos (ni aspiran a serlo)
  - “el ppt” (ni  “la ppt”)

- Políticas de participación y trato: se espera y enfatiza la participación por distintos canales disponibles. También se enfatiza un trato respetuoso y horizontal. Quienes están tomando este curso serán referidos como participantes y/o estudiantes, evitar el uso de “l_s cabr_s” o “l_s chiquill_s”, que si bien puede intentar transmitir cercanía finalmente expresan minimización de la contraparte. Quien no se sienta tratad_ apropiadamente o vea que otr_s no lo están siendo, se solicita reportar para solucionar la situación.


## Programación de sesiones

Visitar la página de [Planificación](schedule.html).
