---
title: "Evaluación Grupo 1"
lang: es
number-sections: true
---

Esta pauta se aplica al **Trabajo 2: Informe final**.

## Puntaje, rúbrica y evaluación

La evaluación se realiza sobre **6 puntos**, más **1 punto base**, para un total de **7 puntos**. Además, el pre-print cumple como puntaje de bonificación de 0.5 décimas para los grupos que lo hayan realizado.

::: {style="overflow-x: auto;"}
| Sección | Criterios | Máx. | Obtenido | Comentarios |
|---------------|---------------|--------------:|--------------:|---------------|
| **1. Abstract** | Resume problema de investigación, contexto teórico mínimo y estrategia empírica. Discute los alcances y límites del proyecto abierto. Síntesis clara de resultados principales. | 0.5 | 0.45 | El abstract cumple con su propósito. Resume la investigación desde sus objetivos, datos, métodos y resultados. Podría mejorar con una breve mención de la problemática inicial del estudio. |
| **2. Tema y motivación** | Tema de interés claramente definido dentro de las ciencias sociales. Justificación adecuada de la elección y relevancia. Indica si es un proyecto nuevo o adaptación de trabajo previo. | 0.5 | 0.40 | La sección cumple con su objetivo. Se presentan los principales factores asociados al objeto de estudio. Sin embargo, habría sido bueno que se detuvieran a darle más relevancia a cada factor de los cuales se desprenden las hipótesis, pues solamente los justifica una oración. Además, no se señala si el trabajo es inédito o previo. |
| **3. Preguntas e hipótesis** | Al menos dos hipótesis de investigación claramente formuladas. Hipótesis son coherentes con el problema y objeto de estudio. Se indica pre-registro de hipótesis antes del análisis principal. | 0.5 | 0.4 | Las hipótesis están correctamente planteadas. Se desprenden de los antecedentes mencionados y presentan una formulación adecuada. No obstante, es importante señalar que en el apartado de conclusiones se menciona que las hipótesis son confirmadas, lo cual técnicamente no es correcto, ya que las hipótesis no se confirman. |
| **4. Datos abiertos** | Utiliza datos abiertos o públicamente accesibles. Especifica con precisión origen, licencia y condiciones de acceso. Describe procedimiento para obtener los datos. | 0.5 | 0.5 | Se utilizan datos de la Encuesta de Bienestar Social 2023, la cual es de acceso abierto. Se especifican de buena manera los criterios y el tamaño muestrales; no se menciona dónde se almacenan los archivos, aunque se encuentra fácilmente al entrar al repositorio debido al uso del protocolo IPO. |
| **5. Protocolo de investigación** | Describe diseño del estudio, variables y criterios de selección/filtrado. Flujo completo de análisis es reproducible. Sigue estructura IPO (entrada, proceso, salida) o equivalente. | 1.0 | 0.7 | Se especifican cómo se tratan las variables utilizadas en el estudio, sin embargo, hay imprecisiones importantes que no son consideradas. Por ejemplo, los dos índices construidos (satisfacción con la vida y salud mental) tienen valores $a$ \< 0.7, el umbral mínimo de aceptación para un alpha de Cronbach. Si bien uno de ellos puede ser aproximado, se presentan ambos como aceptables, lo cual no es del todo correcto. En estos casos, se sugiere explicitar que las interpretaciones a partir de estas operacionalizaciones deben ser leídas con precaución. Además, habría sido provechoso que se integrara código para verificar las decisiones tomadas en el procesamiento. |
| **6. Prácticas de ciencia abierta** | Proyecto registrado en OSF con documentación clara. Protocolo, hipótesis pre-registradas y materiales relevantes disponibles. Transparencia metodológica y accesibilidad de insumos. | 1.5 | 0.9 | Al momento de ingresar al repositorio, el GitHub Pages no funcionaba correctamente; la página del informe no logró cargar. En caso de haber notado el problema, esto debería haber sido informado previamente al equipo docente, pero finalmente no puede ser evaluado el reporte en formato html si el link no funciona. Además, si bien el pre-registro está bastante detallado en cuanto al procedimiento realizado, se ausenta lo más importante: la presentación explícita de las hipótesis; solamente se explicita la dirección esperada de los betas: b1 \> 0 ; b2 \> 0 ; b3 \> 0 ; b4 \< 0 ; b5 \< 0. Con ello, se pierde gran parte del sentido del pre-registro. |
| **7. Implementación reproducible** | Reporte final desarrollado como Quarto Book. Desplegado en repositorio público. Instrucciones claras para reproducir análisis y regenerar resultados. | 1.5 | 0.75 | El trabajo está construido en un Quarto Book de 8 capítulos, alojado en repositorio público pero sin despliegue para su difusión inmediata. Instrucciones claras para reproducir análisis y generar resultados. No obstante, los resultados descriptivos y bivariados no son acompañados de una figura que respalde su reporte, lo cual reduce de manera importante la reproducibilidad. Además, los resultados mostrados en el modelo de regresión no se condicen con lo expuesto en la sección "Análisis del modelo"; la mayoría de los valores reportados presentan diferencias con lo que señala la tabla, generando incongruencias que no pueden pasarse por alto. |
| **8. Preprint** | Existe preprint del trabajo final disponible públicamente (o justificación en caso de no existir). Versión pública del manuscrito disponible antes o al momento de entrega (por ejemplo, en github pages). Identificador y acceso sin restricciones. | 0.5 | 0 | No se generó pre-print. |
| **Subtotal** |  | **6.0** | **4.10** |  |
| **Punto base** |  | **1.0** | **1.00** |  |
| **Nota final** |  | **7.0** | **5.10** |  |

: {tbl-colwidths="\[13,22,5,6,54\]"}
:::

## Comentario general

El trabajo está orientado a la realización de investigación social desde una perspectiva de ciencia abierta, lo cual queda demostrado mediante el uso de diversas herramientas como Quarto, Zotero, GitHub, entre otras. Si bien esto se valora bastante, la ausencia de figuras para respaldar los resultados, así como la falta de pre-registro de las hipótesis planteadas, representan flancos importantes que reducen la rigurosidad académica de la investigación en el marco de la ciencia abierta. Asimismo, el problema de funcionamiento de GitHub Pages limita de manera importante el acceso a la investigación. En suma, es una buena investigación en términos temáticos, pero que requiere de ajustes importantes para alcanzar los objetivos esperados.