---
title : "The Impact of Open and Reproducible Scholarship on Students’ Scientific Literacy, Engagement, and Attitudes towards Science: A Review and Synthesis of the Evidence"
date : "2022-04-01"
author : ["Madeleine Pownall", "Flavio Azevedo", "Laura M. Konig", "Hannah Rachael Slack", "Thomas Rhys Evans", "Zoe Flack", "Sandra Grinschgl", "Mahmoud Elsherif", "Katie Gilligan-Lee", "Catia Margarida Oliveira", "Biljana Gjoneska", "Tamara Kanadadze", "Kate Button", "Sarah Ashcroft-Jones", "Jenny Terry", "Nihan Albayrak-Aydemir", "Filip Dechterenko", "Shilaan Alzahawi", "Bradley James Baker", "Merle-Marie Pittelkow", "Lydia Riedl", "Kathleen Schmidt", "Charlotte Rebecca Pennington", "John J. Shaw", "Timo Luke", "Matthew C. Makel", "Helena Hartmann", "Mirela Zaneva", "Daniel Walker", "Steven Verheyen", "Daniel Cox", "Jennifer Mattschey", "Thomas Gallagher-Mitchell", "Peter Branney", "Yanna Weisberg", "Kamil Izydorczak", "Ali H. Al-Hoorie", "Ann-Marie Creaven", "Suzanne Stewart", "Kai Krautter", "Karen Matvienko-Sikar", "Samuel Westwood", "Patricia Arriaga", "Meng Liu", "Myriam A. Baum", "Tobias Wingen", "Robert M. Ross", "Aoife O'Mahony", "Agata Bochynska", "Michelle K. Jamieson", "Myrthe Vel Tromp", "Siu Kit Yeung", "Martin Rachev Vasilev", "Amelie Gourdon-Kanhukamwe", "Leticia Micheli", "Markus Konkol", "David Moreau", "James E. Bartlett", "Gwen Brekelmans", "Theofilos Gkinopoulos", "Samantha Tyler", "Jan Philipp Roer", "Zlatomira Ilchovska", "Christopher Madan", "Olly Robertson", "Bethan Iley", "Samuel Guay", "Martina Sladekova", "Shanu Sadhwani", "{FORRT}"]
categories : ["Presentation"]
publication : "  MetaArXiv [https://doi.org/10.31222/osf.io/9e526](https://doi.org/10.31222/osf.io/9e526)"
publication_short : "  MetaArXiv [https://doi.org/10.31222/osf.io/9e526](https://doi.org/10.31222/osf.io/9e526)"
abstract : "In recent years, the scientific community has called for improvements in the credibility, robustness, and reproducibility of research, characterized by higher standards of scientific evidence, increased interest in open practices, and promotion of transparency. While progress has been positive, there is a lack of consideration about how this approach can be embedded into undergraduate and postgraduate research training. Currently, the impact of integrating an open and reproducible approach into the curriculum on student outcomes is not well articulated in the literature. Therefore, in this paper, we provide the first comprehensive review of how integrating open and reproducible scholarship into teaching and learning may impact students, using a large-scale, collaborative, team-science approach. Our review highlighted how embedding open and reproducible scholarship may impact: (1) students’ scientific literacies (i.e., students’ understanding of open research, consumption of science, and the development of transferable skills); (2) student engagement (i.e., motivation and engagement with learning, collaboration, and engagement in open research), and (3) students’ attitudes towards science (i.e., trust in science and confidence in research findings). Our review also identified a need for more robust and rigorous methods within evaluations of teaching practice. We discuss implications for teaching and learning scholarship in this area."
abstract_short : ""
about:
  template: marquee
  links:
    - icon: NA
      href: NA
---


::: {.callout-note title="How to cite this work"}

Madeleine Pownall, Flavio Azevedo, Laura M. Konig, Hannah Rachael Slack, Thomas Rhys Evans, Zoe Flack, Sandra Grinschgl, Mahmoud Elsherif, Katie Gilligan-Lee, Catia Margarida Oliveira, Biljana Gjoneska, Tamara Kanadadze, Kate Button, Sarah Ashcroft-Jones, Jenny Terry, Nihan Albayrak-Aydemir, Filip Dechterenko, Shilaan Alzahawi, Bradley James Baker, Merle-Marie Pittelkow, Lydia Riedl, Kathleen Schmidt, Charlotte Rebecca Pennington, John J. Shaw, Timo Luke, Matthew C. Makel, Helena Hartmann, Mirela Zaneva, Daniel Walker, Steven Verheyen, Daniel Cox, Jennifer Mattschey, Thomas Gallagher-Mitchell, Peter Branney, Yanna Weisberg, Kamil Izydorczak, Ali H. Al-Hoorie, Ann-Marie Creaven, Suzanne Stewart, Kai Krautter, Karen Matvienko-Sikar, Samuel Westwood, Patricia Arriaga, Meng Liu, Myriam A. Baum, Tobias Wingen, Robert M. Ross, Aoife O'Mahony, Agata Bochynska, Michelle K. Jamieson, Myrthe Vel Tromp, Siu Kit Yeung, Martin Rachev Vasilev, Amelie Gourdon-Kanhukamwe, Leticia Micheli, Markus Konkol, David Moreau, James E. Bartlett, Gwen Brekelmans, Theofilos Gkinopoulos, Samantha Tyler, Jan Philipp Roer, Zlatomira Ilchovska, Christopher Madan, Olly Robertson, Bethan Iley, Samuel Guay, Martina Sladekova, Shanu Sadhwani, FORRT (2022). *The Impact of Open and Reproducible Scholarship on Students’ Scientific Literacy, Engagement, and Attitudes towards Science: A Review and Synthesis of the Evidence*.   MetaArXiv [https://doi.org/10.31222/osf.io/9e526](https://doi.org/10.31222/osf.io/9e526)

:::

