---
title: "Evaluación Grupo 4"
lang: es
number-sections: true
---

Esta pauta se aplica al **Trabajo 2: Informe final**.

## Puntaje, rúbrica y evaluación

La evaluación se realiza sobre **6 puntos**, más **1 punto base**, para un total de **7 puntos**.

::: {style="overflow-x: auto;"}
| Sección | Criterios | Máx. | Obtenido | Comentarios |
|---------------|---------------|--------------:|--------------:|---------------|
| **1. Abstract** | Resume problema de investigación, contexto teórico mínimo y estrategia empírica. Discute los alcances y límites del proyecto abierto. Síntesis clara de resultados principales. | 0.5 | 0.45 | El abstract cumple con su propósito. Resume de gran manera la investigación, desde su relevancia, datos, métodos y resultados. Podría mejorar con una breve mención de los alcances, limitaciones y/o cierre integral del estudio. |
| **2. Tema y motivación** | Tema de interés claramente definido dentro de las ciencias sociales. Justificación adecuada de la elección y relevancia. Indica si es un proyecto nuevo o adaptación de trabajo previo. | 0.5 | 0.40 | Tema claramente definido y pertinente de una investigación social. Se presenta una justificación adecuada de la temática, dilucidando un fenómeno global de la contingencia política que es sometido a análisis en el contexto nacional. Sin embargo, no se indica si es un trabajo inédito o previo. |
| **3. Preguntas e hipótesis** | Al menos dos hipótesis de investigación claramente formuladas. Hipótesis son coherentes con el problema y objeto de estudio. Se indica pre-registro de hipótesis antes del análisis principal. | 0.5 | 0.50 | Hipótesis claras en su formulación y pre-registradas en OSF. Se desprenden de los antecedentes presentados y aportan a cumplir los objetivos de la investigación. **Cumple completamente.** |
| **4. Datos abiertos** | Utiliza datos abiertos o públicamente accesibles. Especifica con precisión origen, licencia y condiciones de acceso. Describe procedimiento para obtener los datos. | 0.5 | 0.50 | Utilizan la encuesta CEP N°95, la cual es de libre acceso. Se especifican los criterios y el tamaño muestrales; no se menciona dónde se almacenan los archivos, aunque se encuentra fácilmente al entrar al repositorio debido al uso del protocolo IPO. |
| **5. Protocolo de investigación** | Describe diseño del estudio, variables y criterios de selección/filtrado. Flujo completo de análisis es reproducible. Sigue estructura IPO (entrada, proceso, salida) o equivalente. | 1.0 | 1.0 | Protocolo muy detallado que describe diseño, variables (8 variables de caracterización e interés), criterios de selección y procedimiento de recodificación exhaustivo. Sigue estructura IPO clara. Código reproducible adjunto. **Cumple completamente.** |
| **6. Prácticas de ciencia abierta** | Proyecto registrado en OSF con documentación clara. Protocolo, hipótesis pre-registradas y materiales relevantes disponibles. Transparencia metodológica y accesibilidad de insumos. | 1.5 | 1.5 | La investigación cumple de gran manera con criterios de acceso, transparencia y reproducibilidad. El proyecto se encuentra alojado en GitHub con su respectivo deploy en GitHub Pages, además de haber pre-registrado las hipótesis del estudio en OSF. |
| **7. Implementación reproducible** | Reporte final desarrollado como Quarto Book. Desplegado en repositorio público. Instrucciones claras para reproducir análisis y regenerar resultados. | 1.5 | 1.5 | Formato Quarto Book con 8 capítulos. Código reproducible visible con opciones code-fold. Salidas gráficas regenerables y referenciadas. Uso de Zotero para la gestión y reproducibilidad de la bibliografía. Falta README técnico explícito, pero está implícito en la estructura del libro. |
| **8. Preprint** | Existe preprint del trabajo final disponible públicamente (o justificación en caso de no existir). Versión pública del manuscrito disponible antes o al momento de entrega (por ejemplo, en github pages). Identificador y acceso sin restricciones. | 0.5 | 0 | No cuenta con pre-print. |
| **Subtotal** |  | **6.0** | **5.85** |  |
| **Punto base** |  | **1.0** | **1.00** |  |
| **Nota final** |  | **7.0** | **6.85** |  |

: {tbl-colwidths="\[13,22,5,6,54\]"}
:::

## Comentario general

El informe destaca por un gran nivel de rigurosidad académica; los antecedentes fundamentan el problema de investigación y las hipótesis planteadas permiten dar una respuesta plausible. Además, el proyecto es altamente reproducible al contar con datos públicos accesibles, una buena documentación del procesamiento y posterior análisis de los datos y el despliegue del proyecto en diversas plataformas orientadas a la ciencia abierta (GitHub y OSF). Se recomienda: (1) explicitar el cierre de la investigación en el abstract (2) fortalecer la documentación técnica del repositorio dentro de un READme más detallado. En suma, el trabajo exhibe un cumplimiento satisfactorio de los criterios de ciencia abierta. Felicitaciones por su gran trabajo.