---
title: "Evaluación Grupo 3"
lang: es
number-sections: true
---

Esta pauta se aplica al **Trabajo 2: Informe final**.

## Puntaje, rúbrica y evaluación

La evaluación se realiza sobre **6 puntos**, más **1 punto base**, para un total de **7 puntos**. Además, el pre-print cumple como puntaje de bonificación de 0.5 décimas para los grupos que lo hayan realizado.

::: {style="overflow-x: auto;"}
| Sección | Criterios | Máx. | Obtenido | Comentarios |
|---------------|---------------|--------------:|--------------:|---------------|
| **1. Abstract** | Resume problema de investigación, contexto teórico mínimo y estrategia empírica. Discute los alcances y límites del proyecto abierto. Síntesis clara de resultados principales. | 0.5 | 0.3 | El abstract es bastante sintético, lo que no permite dar cuenta de todos los elementos centrales de la investigación. Por ejemplo, no se introduce la problemática y/o relevancia de la investigación, y además falta mencionar la base de datos con la cual trabajan. |
| **2. Tema y motivación** | Tema de interés claramente definido dentro de las ciencias sociales. Justificación adecuada de la elección y relevancia. Indica si es un proyecto nuevo o adaptación de trabajo previo. | 0.5 | 0.45 | Los apartados que respaldan teórica y empíricamente la investigación cumplen su propósito. No obstante, habría sido ideal ahondar un poco más especialmente en los factores asociados, donde cada uno de ellos es justificado con sólo una frase dentro del último párrafo de antecedentes. |
| **3. Preguntas e hipótesis** | Al menos dos hipótesis de investigación claramente formuladas. Hipótesis son coherentes con el problema y objeto de estudio. Se indica pre-registro de hipótesis antes del análisis principal. | 0.5 | 0.45 | Las hipótesis se desprenden de los antecedentes previamente presentados. En general, están bien planteadas. Solamente aclarar que las hipótesis de investigación no deben contener adjetivos tales como: *un aumento drástico* ($H_{3}$). |
| **4. Datos abiertos** | Utiliza datos abiertos o públicamente accesibles. Especifica con precisión origen, licencia y condiciones de acceso. Describe procedimiento para obtener los datos. | 0.5 | 0.5 | Se utiliza ELSOC, la cual es una base de datos que cuenta con acceso abierto. Se explica de buena manera el diseño muestral implementado en el estudio, la ola que utilizan y el N que contiene la ola a analizar. |
| **5. Protocolo de investigación** | Describe diseño del estudio, variables y criterios de selección/filtrado. Flujo completo de análisis es reproducible. Sigue estructura IPO (entrada, proceso, salida) o equivalente. | 1.0 | 1.0 | El apartado metodológico explica de buena manera las variables a utilizar junto con su respectiva operacionalización. Sin embargo, en el apartado de resultados no se presenta el modelo en el cual se basa la interpretación de tal sección. Esto constituye un problema en cuanto a la reproducibilidad debido a la imposibilidad de regenerar el output que presenta los hallazgos (modelo de regresión). Como sugerencia, los resultados siempre deben ir acompañados de su respectiva figura, incluso puede ir en la sección de anexos, pero la ausencia de esto le resta rigurosidad y reproducibilidad a la investigación. |
| **6. Prácticas de ciencia abierta** | Proyecto registrado en OSF con documentación clara. Protocolo, hipótesis pre-registradas y materiales relevantes disponibles. Transparencia metodológica y accesibilidad de insumos. | 1.5 | 0.75 | Las hipótesis señaladas en el pre-registro son distintas a las del informe, perdiendo el sentido del pre-registro en sí mismo. Además, se señala causalidad cuando el método empleado en el análisis permite descubrir asociaciones, pero no efectos causales. Se recomienda aplicar uniformidad a sus investigaciones, esto es, mantener una sola línea en cómo se plantean sus preguntas, hipótesis y argumentos. Además, tener claridad del alcance que les permiten los métodos empleados en cuanto a la interpretación de resultados (por ejemplo: descripción, inferencia, causalidad). |
| **7. Implementación reproducible** | Reporte final desarrollado como Quarto Book. Desplegado en repositorio público. Instrucciones claras para reproducir análisis y regenerar resultados. | 1.5 | 1.0 | El trabajo está construido en un Quarto Book de 8 capítulos. Desplegado en repositorio público. Instrucciones claras para reproducir análisis y regenerar resultados. No obstante, el hecho de que la tabla principal de resultados no esté disponible le resta reproducibilidad a la investigación. |
| **8. Preprint** | Existe preprint del trabajo final disponible públicamente (o justificación en caso de no existir). Versión pública del manuscrito disponible antes o al momento de entrega (por ejemplo, en github pages). Identificador y acceso sin restricciones. | 0.5 | 0 | No se generó pre-print. |
| **Subtotal** |  | **6.0** | **4.45** |  |
| **Punto base** |  | **1.0** | **1.00** |  |
| **Nota final** |  | **7.0** | **5.45** |  |

: {tbl-colwidths="\[13,22,5,6,54\]"}
:::

## Comentario general

La investigación da cuenta de la implementación de diversos recursos que permiten un alto nivel de apertura, pero presenta faltas importantes en la transparencia y la reproducibilidad. El hecho de pre-registrar hipótesis distintas a las que están en su investigación podría entenderse como manipulación de los planteamientos post análisis de resultados, restándole transparencia. Por otro lado, la falta del modelo que presenta los resultados obstaculiza la reproducción de los análisis. Si bien, queda claro que el proyecto promueve la investigación social abierta, los elementos mencionados dificultan un cumplimiento total de la reproducibilidad. En suma, es una buena investigación en términos temáticos, pero que requiere de ajustes importantes para alcanzar los objetivos esperados.