---
title: "Resumen evaluaciones - Informe Final"
lang: es
---

La siguiente tabla resume los grupos, integrantes, repositorios, informes publicados, preregistro, preprint y nota final del Trabajo 2: Informe Final.

| Grupo | Integrantes | Repositorio | Informe | Evaluación | Preregistro | Preprint | Nota final |
|---|---|---|---|---|---|---|---:|
| Grupo 1 | Bianca Balmaceda, Joaquín Núñez, Amalia Santa | - | - | [Evaluación G1](grupo-1/evaluacion-g1.html){target="_blank"} | Pendiente | Pendiente | Por corregir |
| Grupo 2 | Nicolás Outerbridge, Vicente Rojas | [Repo](https://github.com/x0czz/cohesion-vertical){target="_blank"} | [Informe](https://x0czz.github.io/cohesion-vertical/){target="_blank"} | [Evaluación G2](grupo-2/evaluacion-g2.html){target="_blank"} | Pendiente | Pendiente | Por corregir |
| Grupo 3 | Josefina Bustos, Benjamín Casacuberta | - | - | [Evaluación G3](grupo-3/evaluacion-g3.html){target="_blank"} | Pendiente | Pendiente | Por corregir |
| Grupo 4 | Elisa Calderón, Valentina Montecinos, Amalia Tsukame, Felipe Vega | [Repo](https://github.com/pipoowo/CSA-Trabajo2){target="_blank"} | [Informe](https://pipoowo.github.io/CSA-Trabajo2/docs/){target="_blank"} | [Evaluación G4](grupo-4/evaluacion-g4.html){target="_blank"} | [OSF](https://osf.io/ntjp6/overview){target="_blank"} | Pendiente | 6.9 |
| Grupo 5 | Amaranta González, Amanda Rojo, Elena Yáñez | [Repo](https://github.com/amarantagonzalez-09/evaluacion-final-cienciasocialabierta-grupo5){target="_blank"} | [Informe](https://amarantagonzalez-09.github.io/evaluacion-final-cienciasocialabierta-grupo5/){target="_blank"} | [Evaluación G5](grupo-5/evaluacion-g5.html){target="_blank"} | [OSF](https://osf.io/9r4an/overview){target="_blank"} | Pendiente | 6.1 |
| Grupo 6 | Benjamín Belmar, Renato De Luca, Maite Jullian, Bastián Martín | [Repo](https://github.com/renatodeluca/evaluacion-final-grupo-6){target="_blank"} | [Informe](https://renatodeluca.github.io/evaluacion-final-grupo-6/){target="_blank"} | [Evaluación G6](grupo-6/evaluacion-g6.html){target="_blank"} | [OSF](https://osf.io/4xjye/){target="_blank"} | Pendiente | 7.0 |
| Grupo 7 | Juan Gutiérrez, Eduardo Ortiz, Catalina Parra | [Repo](https://github.com/Sebagarz/trabajo-2-grupo-7){target="_blank"} | [Informe](https://sebagarz.github.io/trabajo-2-grupo-7/){target="_blank"} | [Evaluación G7](grupo-7/evaluacion-g7.html){target="_blank"} | [OSF](https://osf.io/8tbxy){target="_blank"} | Pendiente | 6.4 |
| Grupo 8 | Cristóbal Merchan | [Repo](https://github.com/ElSenorDeLasMoscas/reporte-abierto-cuech){target="_blank"} | [Informe](https://elsenordelasmoscas.github.io/reporte-abierto-cuech/){target="_blank"} | [Evaluación G8](grupo-8/evaluacion-g8.html){target="_blank"} | [OSF](https://osf.io/kv29w){target="_blank"} | Pendiente | 6.35 |
| Grupo 9 | Violeta Mansilla, Francisca Osorio, Martina Soto | [Repo](https://github.com/Fran1129/Trabajo-2){target="_blank"} | [Informe](https://fran1129.github.io/Trabajo-2/){target="_blank"} | [Evaluación G9](grupo-9/evaluacion-g9.html){target="_blank"} | [OSF](https://osf.io/96a3w/overview){target="_blank"} | Pendiente | 5.0 |
| Grupo 10 | Darío Briceño | [Repo](https://github.com/dariobriceno-uch/reporte-conflicto-democracia){target="_blank"} | [Informe](https://dariobriceno-uch.github.io/reporte-conflicto-democracia/){target="_blank"} | [Evaluación G10](grupo-10/evaluacion-g10.html){target="_blank"} | [OSF](https://osf.io/4kun9/overview){target="_blank"} | [SocArXiv](https://osf.io/preprints/socarxiv/65czf_v1){target="_blank"} | 5.85 |

: {tbl-colwidths="[7,20,10,12,12,12,12,8]"}
