---
title: "Resumen Maestro de Correcciones"
subtitle: "Trabajo 1 - Reporte de Reproducibilidad"
lang: es
format:
  html:
    toc: false
    embed-resources: true
---

[Pauta de corrección](/trabajos/pauta-correccion-trabajo1.qmd)

## Tabla Resumen

| Grupo | Repositorio | GitHub Page | Corrección renderizada | Nota |
|---------------|---------------|---------------|---------------|--------------:|
| Grupo 1 | [Trabajo-1.-Cs.-Social-Abierta](https://github.com/santacruzamalia/Trabajo-1.-Cs.-Social-Abierta) | No disponible, [render aquí](/trabajos/informe1/grupo1/Proceso/Trabajo-1.html) | [Corrección G1-Tomás](correccion-trabajo1-G1.html?v=20260516) <br> [Corrección G1-JC](correccion-trabajo1-G1-jc.html) | 6.15 <br> 6.20 |
| Grupo 2 | [Murua_Outerbridge](https://github.com/x0czz/Murua_Outerbridge) | [GitHub Page G2](https://x0czz.github.io/Murua_Outerbridge/) | [Corrección G2-Tomás](correccion-trabajo1-G2.html?v=20260516) <br> [Corrección G2-JC](correccion-trabajo1-G2-jc.html) | 6.90 <br> 6.80 |
| Grupo 3 | [ej-repro-grupo3](https://github.com/josefinabd/ej-repro-grupo3) | No disponible, [render aquí](/trabajos/informe1/grupo3/indexG3.html) | [Corrección G3-Tomás](correccion-trabajo1-G3.html?v=20260516) <br> [Corrección G3-JC](correccion-trabajo1-G3-jc.html) | 7.00 <br> 7.00 |
| Grupo 4 | [CSA-Trabajo1](https://github.com/pipoowo/CSA-Trabajo1) | [GitHub Page G4](https://pipoowo.github.io/CSA-Trabajo1/) | [Corrección G4](correccion-trabajo1-G4.html?v=20260516) | 7.00 |
| Grupo 5 | [cienciasocialabierta-repro-grupo5](https://github.com/sheymn/cienciasocialabierta-repro-grupo5) | [GitHub Page G5](https://sheymn.github.io/cienciasocialabierta-repro-grupo5/) | [Corrección G5](correccion-trabajo1-G5.html?v=20260516) | 6.25 |
| Grupo 6 | [ej-repro-grupo-6](https://github.com/renatodeluca/ej-repro-grupo-6) | [GitHub Page G6](https://renatodeluca.github.io/ej-repro-grupo-6/) | [Corrección G6 - Tomás](https://cienciasocialabierta.netlify.app/trabajos/informe1/correccion-trabajo1-g6?v=20260516) | 6.90 |
| Grupo 7 | [proyecto-casen-grupo7](https://github.com/Sebagarz/proyecto-casen-grupo7) | No disponible, [render aquí](/trabajos/informe1/grupo7/index.html) | [Corrección G7 - Tomás](https://cienciasocialabierta.netlify.app/trabajos/informe1/correccion-trabajo1-g7?v=20260516) | 5.30 |
| Grupo 8 | [ciencia-abierta](https://github.com/ElSenorDeLasMoscas/ciencia-abierta) | [GitHub Page G8](https://elsenordelasmoscas.github.io/ciencia-abierta/index.html) | [Corrección G8 - Tomás](https://cienciasocialabierta.netlify.app/trabajos/informe1/correccion-trabajo1-g8?v=20260516) | 6.15 |
| Grupo 9 | [Trabajo-1](https://github.com/Fran1129/Trabajo-1) | [GitHub Page G9](https://Fran1129.github.io/Trabajo-1/) | [Corrección G9](correccion-trabajo1-G9.html?v=20260516) | 6.40 |
| Grupo 10 | [Reporte1_cienciasocialabierta](https://github.com/dariobriceno-uch/Reporte1_cienciasocialabierta) | No disponible, [render aquí](/trabajos/informe1/grupo10/index.html) | [Corrección G10](correccion-trabajo1-G10.html?v=20260516) | 7.00 |

## Notas

-   Las notas corresponden a la suma directa sobre 7.00 puntos.
-   En GitHub Page se consigna No disponible cuando la URL esperada devolvió 404 al momento de la verificación.