---
title: "Evaluación Grupo 2"
lang: es
number-sections: true
---

Esta pauta se aplica al **Trabajo 2: Informe final**.

## Puntaje, rúbrica y evaluación

La evaluación se realiza sobre **6 puntos**, más **1 punto base**, para un total de **7 puntos**. Además, el pre-print cumple como puntaje de bonificación de 0.5 décimas para los grupos que lo hayan realizado.

::: {style="overflow-x: auto;"}
| Sección | Criterios | Máx. | Obtenido | Comentarios |
|---------------|---------------|--------------:|--------------:|---------------|
| **1. Abstract** | Resume problema de investigación, contexto teórico mínimo y estrategia empírica. Discute los alcances y límites del proyecto abierto. Síntesis clara de resultados principales. | 0.5 | 0.45 | El abstract cumple satisfactoriamente con lo esperado en este apartado. Habría sido ideal comenzar con la problematización y/o relevancia del objeto de estudio, para posteriormente dar paso a los objetivos. |
| **2. Tema y motivación** | Tema de interés claramente definido dentro de las ciencias sociales. Justificación adecuada de la elección y relevancia. Indica si es un proyecto nuevo o adaptación de trabajo previo. | 0.5 | 0.45 | Tema claramente definido y pertinente de una investigación social. Se presenta una justificación adecuada de la temática, dilucidando un fenómeno de la contingencia política que es sometido a análisis en el contexto nacional. Sin embargo, no se indica si es un trabajo inédito o previo. |
| **3. Preguntas e hipótesis** | Al menos dos hipótesis de investigación claramente formuladas. Hipótesis son coherentes con el problema y objeto de estudio. Se indica pre-registro de hipótesis antes del análisis principal. | 0.5 | 0.5 | Las hipótesis se desprenden de los antecedentes previamente presentados. Están bien formuladas en términos académicos. Se sugiere no mencionar elementos estadísticos en las hipótesis (ej. los coeficientes), sino solamente señalar los efectos esperados en relación a las variables dispuestas. |
| **4. Datos abiertos** | Utiliza datos abiertos o públicamente accesibles. Especifica con precisión origen, licencia y condiciones de acceso. Describe procedimiento para obtener los datos. | 0.5 | 0.5 | Se utiliza ELSOC, la cual es una base de datos que cuenta con acceso abierto. Se explica detalladamente el diseño muestral implementado en el estudio, las olas que utilizan y la muestra analítica. |
| **5. Protocolo de investigación** | Describe diseño del estudio, variables y criterios de selección/filtrado. Flujo completo de análisis es reproducible. Sigue estructura IPO (entrada, proceso, salida) o equivalente. | 1.0 | 1.0 | Protocolo de alto nivel, especificando claramente el tratamiento de variables, criterios de selección y procedimiento de recodificación de manera exhaustiva. Se presenta explícitamente la estructura y ubicación de archivos. Código reproducible adjunto en anexos. |
| **6. Prácticas de ciencia abierta** | Proyecto registrado en OSF con documentación clara. Protocolo, hipótesis pre-registradas y materiales relevantes disponibles. Transparencia metodológica y accesibilidad de insumos. | 1.5 | 1.5 | La investigación cumple de gran manera con criterios de acceso, transparencia y reproducibilidad. El proyecto se encuentra alojado en GitHub con su respectivo deploy en GitHub Pages y un READme que vuelve posible que el repositorio sea autoexplicativo, lo cual es sumamente valioso para la reproducibilidad. Además, las hipótesis del estudio fueron pre-registradas en OSF junto a los demás detalles de la investigación. |
| **7. Implementación reproducible** | Reporte final desarrollado como Quarto Book. Desplegado en repositorio público. Instrucciones claras para reproducir análisis y regenerar resultados. | 1.5 | 1.4 | Formato Quarto Book con 8 capítulos principales y 3 adicionales de anexos. Código reproducible visible con opciones code-fold. Salidas gráficas regenerables y referenciadas. Uso de Zotero para la gestión y reproducibilidad de la bibliografía. Proyecto autoexplicativo gracias al READme y el detalle minucioso de las decisiones tomadas para el análisis. No obstante, el trabajo presenta varias faltas ortográficas que reducen su rigurosidad académica |
| **8. Preprint** | Existe preprint del trabajo final disponible públicamente (o justificación en caso de no existir). Versión pública del manuscrito disponible antes o al momento de entrega (por ejemplo, en github pages). Identificador y acceso sin restricciones. | 0.5 | 0 | No se generó pre-print. |
| **Subtotal** |  | **6.0** | **5.8** |  |
| **Punto base** |  | **1.0** | **1.0** |  |
| **Nota final** |  | **7.0** | **6.8** |  |

: {tbl-colwidths="\[13,22,5,6,54\]"}
:::

## Comentario general

El informe cumple satisfactoriamente los objetivos esperados de la entrega; los antecedentes fundamentan el problema de investigación y las hipótesis planteadas permiten dar una respuesta plausible. Además, el proyecto es altamente reproducible al contar con datos públicos accesibles, una documentación destacable del procesamiento y posterior análisis de los datos, así como el despliegue del proyecto en diversas plataformas orientadas a la ciencia abierta (GitHub y OSF). Se recomienda. Como sugerencia, se recomienda revisar el escrito una última vez antes de realizar el envío en orden de no pasar por alto desprolijidades. No obstante, el trabajo es indudablemente de un gran nivel en cuanto al análisis realizado y la reproducibilidad alcanzada. Felicitaciones por el gran trabajo.